name: myenv
channels: 
  - conda-forge
  - huggingface
  - pytorch
dependencies:
  - python=3.8
  - flask=2.0.2
  - flask_cors=3.0.10
  - nltk=3.6.5
  - numpy=1.21.2
  - pandas=1.3.5
  - path=16.0.0
  - pytorch=1.10.1
  - pytorch-mutex=1.0
  - tranformers=4.11.3